apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
      - name: medicure
        image: your-dockerhub-repo/medicure:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: medicure-staging-service
spec:
  selector:
    app: medicure
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
